In [2]:
import pandas as pd
from epiweeks import Week

In [4]:
geo_dengue = [2931350,2933307,2302503,3119401,
              3549805,3541406,1200401,1200203,
              1716109,4113700,4103701,4104808,
              5201405,5102637,5215231]

geo_chik = [2211001,2931350,3143302,3119401,
            1721000,1716109,4104808,4219507,
            5103403,5102637]

In [18]:
df_dengue = pd.read_csv('../../imdc_2026/dengue_update.csv.gz')
df_dengue = df_dengue.loc[df_dengue.geocode.isin(geo_dengue)][['date', 'geocode', 'casos']].rename(columns = {'geocode': 'adm_2'})
df_dengue.head()

            date    adm_2  casos
493   2010-01-03  4113700     14
841   2010-01-03  2302503      0
1501  2010-01-03  4103701      0
3117  2010-01-03  3541406      4
3216  2010-01-03  3119401      8

In [19]:
df_dengue.to_csv('dengue_city.csv.gz', index = False)

In [10]:
df_old = pd.read_csv('chik_city.csv.gz')
df_old.date = pd.to_datetime(df_old.date)
df_old.head()

        date    adm_2  casos
0 2013-12-29  3143302      0
1 2013-12-29  1716109      0
2 2013-12-29  1721000      0
3 2013-12-29  3119401      0
4 2013-12-29  5102637      0

In [11]:
df_old.loc[df_old.date == pd.to_datetime(Week(2023,24).startdate())]

           date    adm_2  casos
4930 2023-06-11  3143302     23
4931 2023-06-11  5102637      0
4932 2023-06-11  2931350     33
4933 2023-06-11  1716109      2
4934 2023-06-11  4104808      0
4935 2023-06-11  5103403      0
4936 2023-06-11  3119401     18
4937 2023-06-11  2211001     47
4938 2023-06-11  1721000     25
4939 2023-06-11  4219507      0

In [13]:
df_new = pd.read_csv('../../imdc_2026/chikungunya_update.csv.gz')
df_new = df_new.loc[df_new.geocode.isin(geo_chik)][['date', 'geocode', 'casos']].rename(columns = {'geocode': 'adm_2'})
#df_new = df_new.groupby(['date', 'uf_code'])[['casos']].sum().reset_index().rename(columns = {'uf_code': 'adm_1'})
df_new.date = pd.to_datetime(df_new.date)
df_new.loc[df_new.date>='2023-06-11']

             date    adm_2  casos
6474   2023-06-11  2211001     47
6960   2023-06-11  5102637      0
7391   2023-06-11  5103403      0
8304   2023-06-11  3119401     18
9000   2023-06-11  2931350     33
...           ...      ...    ...
966554 2026-09-27  5102637      0
967336 2026-09-27  2931350      0
967650 2026-09-27  1721000      0
967765 2026-09-27  1716109      0
968249 2026-09-27  2211001      0

[1730 rows x 3 columns]

In [15]:
df_end = pd.concat([df_old.loc[df_old.date <= pd.to_datetime(Week(2023,24).startdate())], df_new.loc[df_new.date>'2023-06-11']])

df_end

             date    adm_2  casos
0      2013-12-29  3143302      0
1      2013-12-29  1716109      0
2      2013-12-29  1721000      0
3      2013-12-29  3119401      0
4      2013-12-29  5102637      0
...           ...      ...    ...
966554 2026-09-27  5102637      0
967336 2026-09-27  2931350      0
967650 2026-09-27  1721000      0
967765 2026-09-27  1716109      0
968249 2026-09-27  2211001      0

[6660 rows x 3 columns]

In [16]:
df_end.to_csv('chik_city.csv.gz', index = False)

In [ ]:
df_new.to_csv('dengue_state.csv.gz', index = False)

In [ ]:
df = pd.read_csv('dengue_state.csv.gz')
df.head()

         date  adm_1  casos
0  2010-01-03     11   2456
1  2010-01-03     12    760
2  2010-01-03     13    155
3  2010-01-03     14     25
4  2010-01-03     15    115