In [1]:
import pandas as pd

In [8]:
df_new = pd.read_csv('../../imdc_2026/dengue_update.csv.gz')
df_new = df_new.groupby(['date', 'uf_code'])[['casos']].sum().reset_index().rename(columns = {'uf_code': 'adm_1'})
df_new.head()

         date  adm_1  casos
0  2010-01-03     11   2456
1  2010-01-03     12    760
2  2010-01-03     13    155
3  2010-01-03     14     25
4  2010-01-03     15    115

In [9]:
df_new.to_csv('dengue_state.csv.gz', index = False)

In [10]:
df = pd.read_csv('dengue_state.csv.gz')
df.head()

         date  adm_1  casos
0  2010-01-03     11   2456
1  2010-01-03     12    760
2  2010-01-03     13    155
3  2010-01-03     14     25
4  2010-01-03     15    115